baseURL = "/"
languageCode = "en-gb"
title = "David Mark H"
theme = "PaperMod"
canonifyURLs = true
relativeURLs = false
uglyURLs = false

[params]
  author = "admim"
  description = "Independent Azure Databricks pipeline builds"
  ShowFooter = true
  ShowCopyright = true
  defaultTheme = "dark"
  disableThemeToggle = false


[params.footer]
  text = "Independent work, outside primary employment."

[menu]
  [[menu.footer]]
    name = "Home"
    url = "/"
