baseURL = "https://markdmh.uk/"
languageCode = "en-gb"
title = "David Mark H"
theme = "PaperMod"
canonifyURLs = true
relativeURLs = false

[params]
  author = "admim"
  description = "Independent Azure Databricks pipeline builds"
  ShowFooter = true
  ShowCopyright = true

[params.footer]
  text = "Independent work, outside primary employment."

[menu]
  [[menu.footer]]
    name = "Home"
    url = "/"
